services:
  - type: web
    name: uvg-network-operations
    runtime: docker
    repo: https://github.com/Ninaswiftie09/Redes
    branch: Proyecto1
    plan: free
    region: virginia
    autoDeployTrigger: commit
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    maxShutdownDelaySeconds: 30
    envVars:
      - key: MCP_AUTH_TOKEN
        sync: false
